# -*- coding: utf-8 -*-
"""
🧪 Colab 1 — Build a Financial RAG System
Day 15 · Gen AI APIs · Enterprise AI Engineering Series

Converted from Colab notebook to standalone Python script.
Uses .env file for credentials instead of Colab Secrets.

Industry Scenario: FinSight AI
  You are an engineer at a Tier-1 investment bank building FinSight,
  an AI Research Analyst Assistant. Analysts need to query annual
  reports in natural language.
  Target: faithfulness >= 0.85, latency < 3s, cost < $0.002/query.
"""

import os
import sys
import time

import pandas as pd
from dotenv import load_dotenv

# ─────────────────────────────────────────────────────────────────────────────
# Step 1 — Load Credentials from .env
# ─────────────────────────────────────────────────────────────────────────────

# Walk up to find .env (supports running from day16/ or project root)
_env_path = os.path.join(os.path.dirname(__file__), "..", "..", ".env")
if os.path.exists(_env_path):
    load_dotenv(_env_path)
else:
    load_dotenv()  # fallback: look in cwd

AZURE_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_API_KEY = os.getenv("AZURE_OPENAI_KEY")
AZURE_DEPLOYMENT = os.getenv("AZURE_OPENAI_DEPLOYMENT", "gpt-4o")
AZURE_API_VERSION = os.getenv("AZURE_OPENAI_API_VERSION", "2024-06-01")

if not AZURE_API_KEY or not AZURE_ENDPOINT:
    print("❌ Missing Azure credentials.")
    print("   Set AZURE_OPENAI_ENDPOINT and AZURE_OPENAI_KEY in your .env file.")
    sys.exit(1)

print("✅ Credentials loaded from .env")

# ─────────────────────────────────────────────────────────────────────────────
# Step 2 — Sample SEC 10-K Filing Documents
# ─────────────────────────────────────────────────────────────────────────────

SAMPLE_DOCS = [
    {
        "source": "Apple_10K_2023_Risk",
        "text": (
            "RISK FACTORS\n"
            "Apple's operations and financial results are subject to various risks and uncertainties.\n"
            "Global and regional economic conditions, including conditions resulting from financial and credit market fluctuations,\n"
            "can adversely affect demand for Apple's products and services.\n"
            "Apple faces intense competition in all of its business areas from well-established companies with significant\n"
            "resources, as well as from new market entrants.\n"
            "Apple depends on the performance of distributors, carriers, wholesalers and other resellers.\n"
            "The Company's fiscal year 2023 revenue was $383.3 billion, compared to $394.3 billion in fiscal 2022,\n"
            "a decrease of approximately 2.8 percent.\n"
            "The Company's net income for fiscal 2023 was $97.0 billion, or $6.13 diluted earnings per share,\n"
            "compared to $99.8 billion, or $6.11 diluted earnings per share, in fiscal 2022.\n"
            "Apple's gross margin percentage was 44.1% in fiscal 2023, compared to 43.3% in fiscal 2022.\n"
            "Services revenue reached an all-time high of $85.2 billion in fiscal 2023, up 9 percent year over year."
        ),
    },
    {
        "source": "Apple_10K_2023_Products",
        "text": (
            "PRODUCTS AND SERVICES\n"
            "Apple designs, manufactures and markets smartphones, personal computers, tablets, wearables and accessories.\n"
            "iPhone is Apple's line of smartphones based on its iOS operating system.\n"
            "iPhone net sales were $200.6 billion in fiscal 2023, representing approximately 52% of total revenue.\n"
            "Mac net sales were $29.4 billion in fiscal 2023, down from $40.2 billion in fiscal 2022.\n"
            "iPad net sales were $28.3 billion in fiscal 2023.\n"
            "Wearables, Home and Accessories net sales were $39.8 billion in fiscal 2023.\n"
            "Apple's Services segment includes advertising, AppleCare, cloud, digital content, payment and other services.\n"
            "The App Store, Apple Music, Apple TV+, Apple Arcade, iCloud and Apple Pay are key Services offerings.\n"
            "The Company had approximately 2.2 billion active devices at the end of fiscal year 2023."
        ),
    },
    {
        "source": "Apple_10K_2023_Liquidity",
        "text": (
            "LIQUIDITY AND CAPITAL RESOURCES\n"
            "The Company believes its existing balances of cash, cash equivalents and unrestricted marketable securities,\n"
            "together with cash generated by operations, will be sufficient to satisfy its expected cash needs.\n"
            "Cash and cash equivalents as of September 30, 2023 were $29.965 billion.\n"
            "Total marketable securities were $100.544 billion, consisting of current marketable securities of $31.590 billion\n"
            "and non-current marketable securities of $100.544 billion.\n"
            "During fiscal 2023, the Company returned over $77 billion to shareholders,\n"
            "including $15.1 billion in dividends and dividend equivalents and $62.2 billion through repurchases of 471 million shares.\n"
            "Capital expenditures were $10.959 billion in fiscal 2023.\n"
            "The Company's long-term debt as of September 30, 2023 was $95.281 billion."
        ),
    },
]

print(f"📂 Loaded {len(SAMPLE_DOCS)} documents")
for doc in SAMPLE_DOCS:
    print(f"  - {doc['source']}: {len(doc['text'])} characters")


# ─────────────────────────────────────────────────────────────────────────────
# Step 3 — Chunking Strategy
# ─────────────────────────────────────────────────────────────────────────────

from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.documents import Document


def create_chunks(
    docs: list, chunk_size: int = 512, chunk_overlap: int = 64
) -> list:
    """Convert raw documents to LangChain Document chunks."""
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap,
        separators=["\n\n", "\n", ". ", " ", ""],
        length_function=len,
    )
    lc_docs = [
        Document(page_content=d["text"], metadata={"source": d["source"]})
        for d in docs
    ]
    chunks = splitter.split_documents(lc_docs)
    return chunks


CHUNK_SIZE = 512
CHUNK_OVERLAP = 64
chunks = create_chunks(SAMPLE_DOCS, CHUNK_SIZE, CHUNK_OVERLAP)

print(f"\n✅ Created {len(chunks)} chunks (size={CHUNK_SIZE}, overlap={CHUNK_OVERLAP})")
print(f"📋 Sample chunk:")
print(f"  Source: {chunks[0].metadata['source']}")
print(f"  Content: {chunks[0].page_content[:200]}...")


# ─────────────────────────────────────────────────────────────────────────────
# Step 4 — Embed with HuggingFace all-MiniLM-L6-v2
# ─────────────────────────────────────────────────────────────────────────────

from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS

print("\n⏳ Loading HuggingFace embedding model...")
embedding_model = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2",
    model_kwargs={"device": "cpu"},
    encode_kwargs={"normalize_embeddings": True, "batch_size": 32},
)

print("⏳ Building FAISS index...")
t0 = time.time()
vectorstore = FAISS.from_documents(chunks, embedding_model)
elapsed = time.time() - t0

print(f"✅ FAISS index built in {elapsed:.2f}s")
print(f"   Vectors: {vectorstore.index.ntotal}")
print(f"   Dimension: {vectorstore.index.d}")


# ─────────────────────────────────────────────────────────────────────────────
# Step 5 — Build the Retriever (MMR)
# ─────────────────────────────────────────────────────────────────────────────

retriever = vectorstore.as_retriever(
    search_type="mmr",
    search_kwargs={
        "k": 4,
        "fetch_k": 10,
        "lambda_mult": 0.7,
    },
)

test_query = "What was Apple revenue in 2023?"
results = retriever.invoke(test_query)
print(f'\n🔍 Query: "{test_query}"')
print(f"   Retrieved {len(results)} chunks:")
for i, r in enumerate(results):
    print(f"   [{i+1}] {r.metadata['source']}: {r.page_content[:100]}...")


# ─────────────────────────────────────────────────────────────────────────────
# Step 6 — Azure OpenAI Generation (RAG Chain)
# ─────────────────────────────────────────────────────────────────────────────

from langchain_openai import AzureChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

llm = AzureChatOpenAI(
    azure_endpoint=AZURE_ENDPOINT,
    azure_deployment=AZURE_DEPLOYMENT,
    openai_api_version=AZURE_API_VERSION,
    openai_api_key=AZURE_API_KEY,
    temperature=0,
    max_tokens=512,
    timeout=30,
)

RAG_PROMPT = ChatPromptTemplate.from_template("""
You are FinSight, an AI research analyst for a Tier-1 investment bank.
Answer the analyst's question ONLY using the provided context.
If the context does not contain the answer, say: "Insufficient information in the retrieved context."
Always cite the specific source document at the end of your answer.

CONTEXT:
{context}

ANALYST QUESTION: {question}

ANSWER (cite source):
""")


def format_docs(docs):
    return "\n\n".join(
        f"[Source: {d.metadata['source']}]\n{d.page_content}" for d in docs
    )


rag_chain = (
    {"context": retriever | format_docs, "question": RunnablePassthrough()}
    | RAG_PROMPT
    | llm
    | StrOutputParser()
)

print("\n✅ RAG chain built")


# ─────────────────────────────────────────────────────────────────────────────
# Step 7 — Run Queries & Measure Latency
# ─────────────────────────────────────────────────────────────────────────────

TEST_QUERIES = [
    "What was Apple's total revenue in fiscal year 2023?",
    "How much cash did Apple have at the end of fiscal 2023?",
    "What percentage of Apple's revenue came from iPhone in 2023?",
    "How much did Apple return to shareholders in fiscal 2023?",
    "What is Apple's gross margin for fiscal 2023?",
]

results_log = []

print("\n" + "=" * 70)
print("🧪  Running RAG queries...")
print("=" * 70)

for query in TEST_QUERIES:
    t0 = time.time()
    answer = rag_chain.invoke(query)
    latency = time.time() - t0
    results_log.append(
        {"query": query, "answer": answer, "latency_s": round(latency, 2)}
    )
    print(f"\n❓ {query}")
    print(f"   ⏱️  {latency:.2f}s")
    print(f"   💬 {answer[:200]}...")


# ─────────────────────────────────────────────────────────────────────────────
# Step 8 — RAGAS Evaluation
# ─────────────────────────────────────────────────────────────────────────────

from datasets import Dataset
from ragas import evaluate
from ragas.metrics import (
    faithfulness,
    answer_relevancy,
    context_recall,
    context_precision,
)
from langchain_openai import AzureOpenAIEmbeddings

GROUND_TRUTHS = [
    "Apple's total revenue in fiscal 2023 was $383.3 billion.",
    "Apple had $29.965 billion in cash and cash equivalents at end of fiscal 2023.",
    "iPhone represented approximately 52% of Apple's total revenue in fiscal 2023.",
    "Apple returned over $77 billion to shareholders in fiscal 2023.",
    "Apple's gross margin was 44.1% in fiscal 2023.",
]

contexts_used = []
for q in TEST_QUERIES:
    docs = retriever.invoke(q)
    contexts_used.append([d.page_content for d in docs])

eval_dataset = Dataset.from_dict(
    {
        "question": TEST_QUERIES,
        "answer": [r["answer"] for r in results_log],
        "contexts": contexts_used,
        "ground_truth": GROUND_TRUTHS,
    }
)

AZURE_EMBEDDING_DEPLOYMENT = os.getenv(
    "AZURE_OPENAI_EMBEDDING_DEPLOYMENT", "text-embedding-ada-002"
)

az_embeddings = AzureOpenAIEmbeddings(
    azure_endpoint=AZURE_ENDPOINT,
    azure_deployment=AZURE_EMBEDDING_DEPLOYMENT,
    openai_api_key=AZURE_API_KEY,
    openai_api_version=AZURE_API_VERSION,
)

print("\n⏳ Running RAGAS evaluation...")
ragas_results = evaluate(
    dataset=eval_dataset,
    metrics=[faithfulness, answer_relevancy, context_recall, context_precision],
    llm=llm,
    embeddings=az_embeddings,
)

print("\n📊 RAGAS Evaluation Results:")
print(ragas_results)


# ─────────────────────────────────────────────────────────────────────────────
# Step 9 — Chunk Size Experiment
# ─────────────────────────────────────────────────────────────────────────────

CHUNK_SIZES_TO_TEST = [256, 512, 1024]
experiment_results = []

print("\n" + "=" * 70)
print("🔬 Chunk Size Experiment")
print("=" * 70)

for cs in CHUNK_SIZES_TO_TEST:
    print(f"\n🔧 Testing chunk_size={cs}...")

    exp_chunks = create_chunks(SAMPLE_DOCS, chunk_size=cs, chunk_overlap=cs // 8)
    exp_vs = FAISS.from_documents(exp_chunks, embedding_model)
    exp_retriever = exp_vs.as_retriever(
        search_type="mmr", search_kwargs={"k": 4, "fetch_k": 10}
    )

    exp_chain = (
        {"context": exp_retriever | format_docs, "question": RunnablePassthrough()}
        | RAG_PROMPT
        | llm
        | StrOutputParser()
    )

    answers, latencies = [], []
    for q in TEST_QUERIES[:3]:  # subset to save cost
        t0 = time.time()
        a = exp_chain.invoke(q)
        latencies.append(time.time() - t0)
        answers.append(a)

    experiment_results.append(
        {
            "chunk_size": cs,
            "n_chunks": len(exp_chunks),
            "avg_latency_s": round(sum(latencies) / len(latencies), 2),
        }
    )
    print(
        f"   Chunks: {len(exp_chunks)}, "
        f"Avg latency: {experiment_results[-1]['avg_latency_s']}s"
    )

df_exp = pd.DataFrame(experiment_results)
print("\n📊 Chunk Size Comparison:")
print(df_exp.to_string(index=False))
print(
    "\n💡 Tip: Run full RAGAS evaluation per chunk_size "
    "to see faithfulness trade-offs"
)


# ─────────────────────────────────────────────────────────────────────────────
# Extension: Hybrid Retrieval & Cross-Encoder Re-Ranking
# ─────────────────────────────────────────────────────────────────────────────

from langchain_community.retrievers import BM25Retriever
from langchain_classic.retrievers import EnsembleRetriever
from langchain_classic.retrievers.document_compressors import CrossEncoderReranker
from langchain_community.cross_encoders import HuggingFaceCrossEncoder
from langchain_classic.retrievers import ContextualCompressionRetriever

print("\n" + "=" * 70)
print("🚀 Running Extension: Hybrid Retrieval + Re-Ranking")
print("=" * 70)

print("⏳ Building BM25 Retriever...")
bm25_retriever = BM25Retriever.from_documents(chunks)
bm25_retriever.k = 4

print("⏳ Combining into Hybrid Ensemble (60% Dense, 40% Sparse)...")
hybrid_retriever = EnsembleRetriever(
    retrievers=[retriever, bm25_retriever],
    weights=[0.6, 0.4],  # 60% dense, 40% BM25
)

print("⏳ Loading Cross-Encoder Re-Ranker...")
cross_encoder = HuggingFaceCrossEncoder(model_name="cross-encoder/ms-marco-MiniLM-L-6-v2")
reranker = CrossEncoderReranker(model=cross_encoder, top_n=3)

compression_retriever = ContextualCompressionRetriever(
    base_compressor=reranker,
    base_retriever=hybrid_retriever
)

ext_query = "What was Apple net income in fiscal 2023?"
print(f'\n🔍 Extension Query: "{ext_query}"')

t0 = time.time()
hybrid_results = compression_retriever.invoke(ext_query)
ext_latency = time.time() - t0

print(f"   ⏱️ Retrieved and Re-Ranked {len(hybrid_results)} chunks in {ext_latency:.2f}s")
for i, r in enumerate(hybrid_results):
    print(f"   [{i+1}] {r.metadata['source']}: {r.page_content[:100]}...")

print("\n✅ Pipeline complete!")
